apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8fxj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8fxj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8fxj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8fxj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8fxj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ehvh-tenant/rhtap-demo-app/hacbs-test-project-8fxj@sha256:59a913d7c5cf3e2af0784f8a8c49246b1e896b657d91cd77cd4dd30dfcba8b53
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
